### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kljunowsky** [mr-medi/HostPanic#2]
Respected author, please add a license!

**Comment by mr-medi** [comment]
Hi @kljunowsky, sorry for the delay.

During this week i will update this project with a license.
If you have any more question or any idea about this project feel free to let me know :)

Thanks a lot for your feedback, I really appreciate it.

Best regards

**Comment by kljunowsky** [comment]
Hi @mr-medi, it's okay!
I would suggest you MIT License for this project.

Best,
Kljunowsky

**Comment by mr-medi** [comment]
Hi @kljunowsky ,

I added the MIT License for this project, thanks a lot for the suggestion.

Best regards,
Medi
